/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CASHIER_FRAME;


import javax.swing.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author joeya
 */
public class ADMIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ADMIN.class.getName());
    private String currentUsername;

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
        startClock(lblDATE, lblTIME);
        loadDashboardTableAndSummary();


    }
    
    
    public ADMIN(String username) {
        initComponents();        
        this.currentUsername = username;
        startClock(lblDATE, lblTIME);
        loadDashboardTableAndSummary();
        lblWelcome.setText( currentUsername + "!");

    }
    
    private void startClock(JLabel lblDate, JLabel lblTime) {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
                lblTime.setText(timeFormat.format(now));
                lblDate.setText(dateFormat.format(now));
            }
        });
        timer.start();
    }
    
    public String getCurrentUsername() {
        return currentUsername;
    }
    
    private void logActivity(String username, String action) {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123")) {
            String sql = "INSERT INTO activity_logs (username, action) VALUES (?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, action);
            pst.executeUpdate();
            pst.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUSERMANAGEMENT = new javax.swing.JButton();
        btnACTIVITYLOG = new javax.swing.JButton();
        btnSALESREPORT = new javax.swing.JButton();
        btnHOME = new javax.swing.JButton();
        btnLOGOUT = new javax.swing.JButton();
        lblDATE = new javax.swing.JLabel();
        lblTIME = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboardSales = new javax.swing.JTable();
        lblTotalSalesToday = new javax.swing.JLabel();
        lblTotalItemsToday = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUSERMANAGEMENT.setBackground(new java.awt.Color(59, 105, 133));
        btnUSERMANAGEMENT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUSERMANAGEMENT.setForeground(new java.awt.Color(255, 255, 255));
        btnUSERMANAGEMENT.setText("USER MANAGEMENT");
        btnUSERMANAGEMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSERMANAGEMENTActionPerformed(evt);
            }
        });
        getContentPane().add(btnUSERMANAGEMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 70));

        btnACTIVITYLOG.setBackground(new java.awt.Color(59, 105, 133));
        btnACTIVITYLOG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnACTIVITYLOG.setForeground(new java.awt.Color(255, 255, 255));
        btnACTIVITYLOG.setText("ACTIVITY LOG");
        btnACTIVITYLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACTIVITYLOGActionPerformed(evt);
            }
        });
        getContentPane().add(btnACTIVITYLOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, 70));

        btnSALESREPORT.setBackground(new java.awt.Color(59, 105, 133));
        btnSALESREPORT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSALESREPORT.setForeground(new java.awt.Color(255, 255, 255));
        btnSALESREPORT.setText("SALES REPORT");
        btnSALESREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALESREPORTActionPerformed(evt);
            }
        });
        getContentPane().add(btnSALESREPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 230, 70));

        btnHOME.setBackground(new java.awt.Color(59, 105, 133));
        btnHOME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHOME.setForeground(new java.awt.Color(255, 255, 255));
        btnHOME.setText("HOME");
        btnHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHOMEActionPerformed(evt);
            }
        });
        getContentPane().add(btnHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 70));

        btnLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Z/LOGINPICTURES/1.png"))); // NOI18N
        btnLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 50, 50));

        lblDATE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDATE.setForeground(new java.awt.Color(59, 105, 133));
        lblDATE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 250, 30));

        lblTIME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTIME.setForeground(new java.awt.Color(59, 105, 133));
        lblTIME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblTIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 170, 30));

        lblWelcome.setFont(new java.awt.Font("Rockwell", 0, 90)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(59, 105, 133));
        lblWelcome.setText("      ");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 490, 130));

        jLabel6.setFont(new java.awt.Font("Vladimir Script", 0, 100)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 105, 133));
        jLabel6.setText("Welcome,");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 350, 130));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 105, 133), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDashboardSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cashier ", "Product ", "Qty ", "Unit Price", "Total ", "Date "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDashboardSales);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 330));

        lblTotalSalesToday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalSalesToday.setForeground(new java.awt.Color(59, 105, 133));
        lblTotalSalesToday.setText("jLabel2");
        jPanel1.add(lblTotalSalesToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 240, 40));

        lblTotalItemsToday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalItemsToday.setForeground(new java.awt.Color(59, 105, 133));
        lblTotalItemsToday.setText("jLabel2");
        jPanel1.add(lblTotalItemsToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 240, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 105, 133));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("=== TODAY'S SALES REPORT  ===");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 790, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 105, 133));
        jLabel3.setText("TOTAL ITEMS TODAY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 105, 133));
        jLabel4.setText("TOTAL SALES TODAY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 840, 480));

        jLabel5.setText("Log out");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 760, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Z/ADMIN/ADMINFRAME.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadDashboardTableAndSummary() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Cashier", "Product", "Qty", "Unit Price", "Total", "Date"}, 0
        );
        tblDashboardSales.setModel(model); // your JTable name

        double totalSales = 0;
        int totalItems = 0;

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123");

            String sql = "SELECT * FROM sales WHERE DATE(timestamp) = CURDATE()";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String cashier = rs.getString("cashier_username");
                String product = rs.getString("product_name");
                int qty = rs.getInt("quantity");
                double unitPrice = rs.getDouble("price");
                double total = rs.getDouble("total");
                String date = rs.getString("timestamp");

                totalSales += total;
                totalItems += qty;

                model.addRow(new Object[]{cashier, product, qty, unitPrice, total, date});
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading dashboard data: " + e.getMessage());
        }

        lblTotalSalesToday.setText("₱ " + String.format("%.2f", totalSales));
        lblTotalItemsToday.setText(String.valueOf(totalItems));
    }

    private void btnUSERMANAGEMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSERMANAGEMENTActionPerformed
        // TODO add your handling code here:
        new USERMANAGEMENT(currentUsername).setVisible(true);       
        this.dispose();

    }//GEN-LAST:event_btnUSERMANAGEMENTActionPerformed

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to logout?",
                "Logout Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            
            logActivity(currentUsername, "Logged out");      
            Login_Frame login = new Login_Frame();                     
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLOGOUTActionPerformed

    private void btnACTIVITYLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACTIVITYLOGActionPerformed
        // TODO add your handling code here:
        Activity_Log logs = new Activity_Log(currentUsername);
        logs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnACTIVITYLOGActionPerformed

    private void btnSALESREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALESREPORTActionPerformed
        // TODO add your handling code here:
        SalesReport report = new SalesReport(currentUsername);
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSALESREPORTActionPerformed

    private void btnHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHOMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ADMIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnACTIVITYLOG;
    private javax.swing.JButton btnHOME;
    private javax.swing.JButton btnLOGOUT;
    private javax.swing.JButton btnSALESREPORT;
    private javax.swing.JButton btnUSERMANAGEMENT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDATE;
    private javax.swing.JLabel lblTIME;
    private javax.swing.JLabel lblTotalItemsToday;
    private javax.swing.JLabel lblTotalSalesToday;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblDashboardSales;
    // End of variables declaration//GEN-END:variables
}
