/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CASHIER_FRAME;

/**
 *
 * @author joeya
 */

import javax.swing.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.swing.*;



public class Login_Frame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login_Frame.class.getName());
    private String currentUsername;


    
    /**
     * Creates new form NewJFrame
     */
    public Login_Frame() {
        initComponents();
        
        
        
    }
    
    

    
    public void login(String username, String password) {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos_system", "root", "admin123"); PreparedStatement pst = conn.prepareStatement("SELECT * FROM users WHERE username=? AND password=?")) {

            pst.setString(1, username);
            pst.setString(2, password);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                
                logActivity(username, "Logged in");
                
                String role = rs.getString("role");
                if ("admin".equals(role)) {
                    new ADMIN().setVisible(true);
                } else if ("cashier".equals(role)) {
                    new POS().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid login.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    private void logActivity(String username, String action) {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123")) {
            String sql = "INSERT INTO activity_logs (username, action) VALUES (?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, action);
            pst.executeUpdate();
            pst.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void setCurrentUsername(String username) {
        this.currentUsername = username;
    }

    
    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUSERNAME = new javax.swing.JTextField();
        txtPASSWORD = new javax.swing.JPasswordField();
        btnENTER = new javax.swing.JButton();
        cbSHOWPASS = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUSERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 310, 40));

        txtPASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 310, 40));

        btnENTER.setBackground(new java.awt.Color(51, 153, 255));
        btnENTER.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnENTER.setForeground(new java.awt.Color(255, 255, 255));
        btnENTER.setText("LOGIN");
        btnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERActionPerformed(evt);
            }
        });
        getContentPane().add(btnENTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 160, 40));

        cbSHOWPASS.setText("SHOW PASSWORD");
        cbSHOWPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSHOWPASSActionPerformed(evt);
            }
        });
        getContentPane().add(cbSHOWPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("USERNAME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Z/LOGINPICTURES/LoginFrame.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public class DBConnection {

        public static Connection getConnection() {
            try {
                String url = "jdbc:mysql://localhost:3306/StudEssentials_POS";
                String user = "root"; // change if you use a different user
                String pass = "admin123"; // your MySQL password

                Class.forName("com.mysql.cj.jdbc.Driver");
                return DriverManager.getConnection(url, user, pass);
            } catch (Exception e) {
                e.printStackTrace();
                return null;
            }
        }
    }

    
    private void btnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERActionPerformed
        // TODO add your handling code here:
        try {
            String username = txtUSERNAME.getText().trim();
            String password = new String(txtPASSWORD.getPassword()).trim();

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123");
            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String role = rs.getString("role");
                String firstName = rs.getString("firstname");  // adjust to your actual column name
                String lastName = rs.getString("surname");     // adjust to your actual column name
                String fullName = firstName + " " + lastName;

                // Show welcome message
                JOptionPane.showMessageDialog(null, "Login successful! Welcome " + fullName + "!");

                // Logging activity
                logActivity(username, "Logged in");

                if (role.equals("admin")) {
                    ADMIN admin = new ADMIN(username);
                    admin.setVisible(true);
                    this.dispose();

                } else if (role.equals("cashier")) {
                    POS ps = new POS();
                    ps.setCurrentUsername(username);
                    ps.setVisible(true);
                    this.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password");
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnENTERActionPerformed

    private void cbSHOWPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSHOWPASSActionPerformed
        // TODO add your handling code here:
        if (cbSHOWPASS.isSelected()) {
            txtPASSWORD.setEchoChar((char) 0);           
        } else {
            txtPASSWORD.setEchoChar('*');           
        }
    }//GEN-LAST:event_cbSHOWPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnENTER;
    private javax.swing.JCheckBox cbSHOWPASS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
