/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CASHIER_FRAME;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author joeya
 */
public class SalesReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesReport.class.getName());
    private String currentUsername;

    /**
     * Creates new form PointOfSale
     */
    public SalesReport(String username) {
        initComponents();
        startClock(lblDATE, lblTIME);        
        this.currentUsername = username;
        
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date from = sdf.parse("2000-01-01");
            Date to = new Date(); // today
            loadSalesReport(from, to, "");
             calculateSalesSummary();
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
    
    public SalesReport() {
        initComponents();
        
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "CASHIER", "PRODUCT", "QTY", "UNIT PRICE", "TOTAL", "DATE"
                }
        ) {
            Class[] types = new Class[]{
                String.class,
                String.class,
                Integer.class,
                Double.class,
                Double.class,
                java.sql.Timestamp.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            
        });             
        
        txtSEARCH.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                toggleClearButton();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                toggleClearButton();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                toggleClearButton();
            }
        });

    }
    
    private void startClock(JLabel lblDate, JLabel lblTime) {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
                lblTime.setText(timeFormat.format(now));
                lblDate.setText(dateFormat.format(now));
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHOME = new javax.swing.JButton();
        btnUSERMANAGEMENT = new javax.swing.JButton();
        btnACTIVITYLOG = new javax.swing.JButton();
        btnSALESREPORT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateFromChooser = new com.toedter.calendar.JDateChooser();
        dateToChooser = new com.toedter.calendar.JDateChooser();
        btnFILTER = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        txtSEARCH = new javax.swing.JTextField();
        btnSEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnPRINT = new javax.swing.JButton();
        btnEXPORT = new javax.swing.JButton();
        lblTOTALSALES = new javax.swing.JLabel();
        lblTOTALITEMS = new javax.swing.JLabel();
        btnLOGOUT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDATE = new javax.swing.JLabel();
        lblTIME = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHOME.setBackground(new java.awt.Color(59, 105, 133));
        btnHOME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHOME.setForeground(new java.awt.Color(255, 255, 255));
        btnHOME.setText("HOME");
        btnHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHOMEActionPerformed(evt);
            }
        });
        getContentPane().add(btnHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 70));

        btnUSERMANAGEMENT.setBackground(new java.awt.Color(59, 105, 133));
        btnUSERMANAGEMENT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUSERMANAGEMENT.setForeground(new java.awt.Color(255, 255, 255));
        btnUSERMANAGEMENT.setText("USER MANAGEMENT");
        btnUSERMANAGEMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSERMANAGEMENTActionPerformed(evt);
            }
        });
        getContentPane().add(btnUSERMANAGEMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 70));

        btnACTIVITYLOG.setBackground(new java.awt.Color(59, 105, 133));
        btnACTIVITYLOG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnACTIVITYLOG.setForeground(new java.awt.Color(255, 255, 255));
        btnACTIVITYLOG.setText("ACTIVITY LOG");
        btnACTIVITYLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACTIVITYLOGActionPerformed(evt);
            }
        });
        getContentPane().add(btnACTIVITYLOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, 70));

        btnSALESREPORT.setBackground(new java.awt.Color(59, 105, 133));
        btnSALESREPORT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSALESREPORT.setForeground(new java.awt.Color(255, 255, 255));
        btnSALESREPORT.setText("SALES REPORT");
        btnSALESREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALESREPORTActionPerformed(evt);
            }
        });
        getContentPane().add(btnSALESREPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 230, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 105, 133));
        jLabel1.setText("Date From:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 105, 133));
        jLabel2.setText("Date To:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 100, 30));
        getContentPane().add(dateFromChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 160, -1));
        getContentPane().add(dateToChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, -1));

        btnFILTER.setText("Filter");
        btnFILTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFILTERActionPerformed(evt);
            }
        });
        getContentPane().add(btnFILTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        btnCLEAR.setText("X");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });
        getContentPane().add(btnCLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 40, 40));
        getContentPane().add(txtSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 290, 40));

        btnSEARCH.setText("SEARCH");
        btnSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(btnSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, -1, 40));

        tblSales.setForeground(new java.awt.Color(59, 105, 133));
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CASHIER", "PRODUCT", "QTY", "UNIT PRICE", "TOTAL", "DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 850, 460));

        btnPRINT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPRINT.setForeground(new java.awt.Color(59, 105, 133));
        btnPRINT.setText("PRINT");
        btnPRINT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 105, 133), 4));
        btnPRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRINTActionPerformed(evt);
            }
        });
        getContentPane().add(btnPRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 730, 90, 60));

        btnEXPORT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEXPORT.setForeground(new java.awt.Color(59, 105, 133));
        btnEXPORT.setText("EXPORT");
        btnEXPORT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 105, 133), 4));
        btnEXPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXPORTActionPerformed(evt);
            }
        });
        getContentPane().add(btnEXPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 730, 90, 60));

        lblTOTALSALES.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTOTALSALES.setForeground(new java.awt.Color(59, 105, 133));
        lblTOTALSALES.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblTOTALSALES, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 330, 60));

        lblTOTALITEMS.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTOTALITEMS.setForeground(new java.awt.Color(59, 105, 133));
        lblTOTALITEMS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblTOTALITEMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 250, 60));

        btnLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Z/LOGINPICTURES/1.png"))); // NOI18N
        btnLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 50, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 105, 133));
        jLabel4.setText("TOTAL SALES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 105, 133));
        jLabel5.setText("TOTAL ITEMS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 100, -1));

        lblDATE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDATE.setForeground(new java.awt.Color(59, 105, 133));
        lblDATE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 250, 30));

        lblTIME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTIME.setForeground(new java.awt.Color(59, 105, 133));
        lblTIME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblTIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 170, 30));

        jLabel6.setText("Log out");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 760, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Z/ADMIN/ADMINFRAME.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void logActivity(String username, String action) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123");
            String sql = "INSERT INTO activity_logs (username, action, timestamp) VALUES (?, ?, NOW())";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, action);
            pst.executeUpdate();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to log activity: " + e.getMessage());
        }
    }

    private void toggleClearButton() {
        String text = txtSEARCH.getText();
        btnCLEAR.setVisible(!text.trim().isEmpty());
    }
        
    private Date getDateFromChooser() {
        return dateFromChooser.getDate(); // JDateChooser variable name
    }

    private Date getDateToChooser() {
        return dateToChooser.getDate();
    }
    
    
    public void loadSalesReport(Date from, Date to, String search) {
        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/StudEssentials_POS", "root", "admin123")) {

            String sql = "SELECT cashier_username, product_name, quantity, price, total, timestamp "
                    + "FROM sales WHERE timestamp BETWEEN ? AND ? AND product_name LIKE ?";

            PreparedStatement pst = con.prepareStatement(sql);
            // From date: start of the day
            Calendar calFrom = Calendar.getInstance();
            calFrom.setTime(from);
            calFrom.set(Calendar.HOUR_OF_DAY, 0);
            calFrom.set(Calendar.MINUTE, 0);
            calFrom.set(Calendar.SECOND, 0);
            calFrom.set(Calendar.MILLISECOND, 0);

            // To date: end of the day
            Calendar calTo = Calendar.getInstance();
            calTo.setTime(to);
            calTo.set(Calendar.HOUR_OF_DAY, 23);
            calTo.set(Calendar.MINUTE, 59);
            calTo.set(Calendar.SECOND, 59);
            calTo.set(Calendar.MILLISECOND, 999);

            pst.setTimestamp(1, new java.sql.Timestamp(calFrom.getTimeInMillis()));
            pst.setTimestamp(2, new java.sql.Timestamp(calTo.getTimeInMillis()));
            
            pst.setString(3, "%" + search + "%");
            
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblSales.getModel();
            model.setRowCount(0); // clear table

            int count = 0;
            while (rs.next()) {
                count++;
                model.addRow(new Object[]{
                    rs.getString("cashier_username"),
                    rs.getString("product_name"),
                    rs.getInt("quantity"),
                    rs.getDouble("price"),
                    rs.getDouble("total"),
                    rs.getTimestamp("timestamp")
                });
            }
            System.out.println("Loaded rows: " + count);  // <-- check console output

            rs.close();
            pst.close();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading sales report: " + e.getMessage());
        }
    }

    private void calculateSalesSummary() {
        double totalSales = 0.0;
        int totalItems = 0;

        for (int i = 0; i < tblSales.getRowCount(); i++) {
            Object qtyObj = tblSales.getValueAt(i, 2);    // Qty column
            Object totalObj = tblSales.getValueAt(i, 4);  // Total column

            if (qtyObj != null && totalObj != null) {
                try {
                    int qty = Integer.parseInt(qtyObj.toString());
                    double total = Double.parseDouble(totalObj.toString());

                    totalItems += qty;
                    totalSales += total;
                } catch (NumberFormatException e) {
                    System.out.println("Error parsing row " + i);
                }
            }
        }

        lblTOTALITEMS.setText(String.valueOf(totalItems));
        lblTOTALSALES.setText("₱ " + String.format("%.2f", totalSales));
    }



    
    public void setDefaultDates() {
        Calendar cal = Calendar.getInstance();
        dateToChooser.setDate(cal.getTime());  // Today

        cal.add(Calendar.DAY_OF_MONTH, -7);
        dateFromChooser.setDate(cal.getTime());  // 7 days ago
    }


    
    private void btnFILTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFILTERActionPerformed
        // TODO add your handling code here:
        Date from = getDateFromChooser();
        Date to = getDateToChooser();

        if (from != null && to != null) {
            loadSalesReport(from, to, txtSEARCH.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Please select both From and To dates.");
        }
    }//GEN-LAST:event_btnFILTERActionPerformed

    private void btnSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEARCHActionPerformed
        // TODO add your handling code here:
        Date from = getDateFromChooser();
        Date to = getDateToChooser();

        if (from != null && to != null) {
            loadSalesReport(from, to, txtSEARCH.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Please select both From and To dates.");
        }
    }//GEN-LAST:event_btnSEARCHActionPerformed

    private void btnPRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRINTActionPerformed
        // TODO add your handling code here:
        try {
            // Format current date and time
            Date now = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy - hh:mm a");

            // Create header with title and date
            MessageFormat header = new MessageFormat("Sales Report - Printed on " + sdf.format(now));
            MessageFormat footer = new MessageFormat("Page {0}");

            boolean complete = tblSales.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            if (complete) {
                JOptionPane.showMessageDialog(this, "Printing completed!");
            } else {
                JOptionPane.showMessageDialog(this, "Printing cancelled.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Printing failed: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnPRINTActionPerformed

    private void btnEXPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXPORTActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Sales Report");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            try (PrintWriter pw = new PrintWriter(new FileWriter(fileToSave + ".csv"))) {
                // Header
                for (int i = 0; i < tblSales.getColumnCount(); i++) {
                    pw.print(tblSales.getColumnName(i));
                    if (i != tblSales.getColumnCount() - 1) {
                        pw.print(",");
                    }
                }
                pw.println();

                // Rows
                for (int i = 0; i < tblSales.getRowCount(); i++) {
                    for (int j = 0; j < tblSales.getColumnCount(); j++) {
                        pw.print(tblSales.getValueAt(i, j));
                        if (j != tblSales.getColumnCount() - 1) {
                            pw.print(",");
                        }
                    }
                    pw.println();
                }

                JOptionPane.showMessageDialog(this, "Sales report exported successfully!");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error exporting file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEXPORTActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        // TODO add your handling code here:
        txtSEARCH.setText("");
        toggleClearButton();
        btnCLEAR.setVisible(true);

        // Optionally reload full table
        Date from = getDateFromChooser();
        Date to = getDateToChooser();
        if (from != null && to != null) {
            loadSalesReport(from, to, "");  // Reload all data
        }
    }//GEN-LAST:event_btnCLEARActionPerformed

    private void btnHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHOMEActionPerformed
        // TODO add your handling code here:
        ADMIN admin = new ADMIN(currentUsername);
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHOMEActionPerformed

    private void btnUSERMANAGEMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSERMANAGEMENTActionPerformed
        // TODO add your handling code here:
        new USERMANAGEMENT(currentUsername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUSERMANAGEMENTActionPerformed

    private void btnACTIVITYLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACTIVITYLOGActionPerformed
        // TODO add your handling code here:
        Activity_Log logs = new Activity_Log(currentUsername);
        logs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnACTIVITYLOGActionPerformed

    private void btnSALESREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALESREPORTActionPerformed
        // TODO add your handling code here:
        SalesReport report = new SalesReport(currentUsername);
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSALESREPORTActionPerformed

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {

            logActivity(currentUsername, "Logged out");
            Login_Frame login = new Login_Frame();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnACTIVITYLOG;
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnEXPORT;
    private javax.swing.JButton btnFILTER;
    private javax.swing.JButton btnHOME;
    private javax.swing.JButton btnLOGOUT;
    private javax.swing.JButton btnPRINT;
    private javax.swing.JButton btnSALESREPORT;
    private javax.swing.JButton btnSEARCH;
    private javax.swing.JButton btnUSERMANAGEMENT;
    private com.toedter.calendar.JDateChooser dateFromChooser;
    private com.toedter.calendar.JDateChooser dateToChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDATE;
    private javax.swing.JLabel lblTIME;
    private javax.swing.JLabel lblTOTALITEMS;
    private javax.swing.JLabel lblTOTALSALES;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtSEARCH;
    // End of variables declaration//GEN-END:variables
}
